# Generated by Django 6.1.1 on 2026-09-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uhudDev', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InquirySystem',
            new_name='inquiries',
        ),
    ]
