# Generated by Django 6.1.1 on 2026-09-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uhudDev', '0002_rename_inquirysystem_inquiries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inquiries',
            new_name='Inquiry',
        ),
    ]
