# Generated by Django 6.1.1 on 2026-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhudDev', '0003_rename_inquiries_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(default='new', max_length=20),
        ),
    ]
